INSERT INTO departments (name)
VALUES ("Accounting"),
       ("Customer Service"),
       ("Information Technology"),
       ("Human Resources"),
       ("Logistics"),
       ("Research and Development"),
       ("Marketing");

INSERT INTO roles(title, salary, department_id)
VALUES  ("Accounting Manager", 160000, 1),
        ("Accountant", 110000, 1),
        ("Customer Service Manager", 42000, 2),
        ("Customer Service Associate", 18000, 2),
        ("IT Manager", 130000, 3),
        ("IT Technician", 80000, 3),
        ("HR Manager", 55000, 4),
        ("HR Consultant", 45000, 4),
        ("Logistics Manager", 140000, 5),
        ("Logistics Consultant", 98000, 5),
        ("Lead Researcher", 220000, 6),
        ("Researcher", 180000, 6),
        ("Marketing Manager", 70000, 7),
        ("Marketing Associate", 55000, 7);

INSERT INTO employees(first_name, last_name, role_id, manager_id)
VALUES  ("John", "Acorn", 1, NULL),
        ("Jacob", "Weezer", 2, 1),
        ("April", "White", 2, 1),
        ("Reece", "Oakley", 2, 1),
        ("Caroline", "Scott", 2, 1),
        ("Jason", "Borne", 3, NULL),
        ("Jonas", "Scaletti", 4, 6),
        ("Vito", "Atreyu", 4, 6),
        ("Lenah", "Cobb", 4, 6),
        ("Victoria", "Holm", 4, 6),
        ("Celeste", "King", 4, 6),
        ("Bill", "Johnson", 4, 6),
        ("Doug", "Jones", 4, 6),
        ("Christina", "Walker", 4, 6),
        ("Danny", "Rutt", 5, NULL),
        ("Joeseph", "Winters", 6, 15),
        ("Grace", "Cordell", 6, 15),
        ("Amy", "Louisoix", 7, NULL),
        ("George", "Castello", 8, 18),
        ("Leonard", "Biggs", 8, 18),
        ("Beverly", "Wilkins", 8, 18),
        ("Anton", "Grady", 9, NULL),
        ("Joyce", "Relker", 10, 22),
        ("Lily", "Belkin", 10, 22),
        ("Gordon", "Freeman", 11, NULL),
        ("Wallace", "Breen", 12, 25),
        ("Eli", "Vance", 12, 25),
        ("Alyx", "Vance", 12, 25),
        ("Gabe", "Newell", 13, NULL),
        ("Todd", "Howard", 14, 29),
        ("Hideo", "Kojima", 14, 29),
        ("Literally", "Who", 14, 29)
        
       